"""analysis completeness

Revision ID: 1eb65025a8b6
Revises: d1b5bdba99a3
Create Date: 2026-09-13 04:18:50.725393

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1eb65025a8b6"
down_revision: str | None = "d1b5bdba99a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("analysis_completeness", sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("analysis_completeness")

    # ### end Alembic commands ###
