"""user profile json

Revision ID: 220d7ae6d4f1
Revises: 1eb65025a8b6
Create Date: 2026-09-13 05:18:10.967524

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "220d7ae6d4f1"
down_revision: str | None = "1eb65025a8b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profile_json", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("profile_json")

    # ### end Alembic commands ###
