"""initial schema

Revision ID: 4cbfde82e2e8
Revises:
Create Date: 2026-09-13 00:05:30.849931

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4cbfde82e2e8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_telegram_user_id"), ["telegram_user_id"], unique=True
        )

    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.Column("source_index", sa.Integer(), nullable=False),
        sa.Column(
            "processing_status",
            sa.Enum(
                "QUEUED",
                "PROCESSING",
                "READY",
                "FAILED",
                name="processingstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "ACTIVE",
                "SNOOZED",
                "DONE",
                "ARCHIVED",
                name="itemstate",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "source_type",
            sa.Enum("TEXT", name="sourcetype", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("processing_stage", sa.String(length=32), nullable=False),
        sa.Column("user_note", sa.Text(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "telegram_message_id", "source_index", name="uq_items_source"
        ),
    )
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_items_processing_status"), ["processing_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_items_telegram_message_id"), ["telegram_message_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_items_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_items_user_id"))
        batch_op.drop_index(batch_op.f("ix_items_telegram_message_id"))
        batch_op.drop_index(batch_op.f("ix_items_processing_status"))

    op.drop_table("items")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_telegram_user_id"))

    op.drop_table("users")
    # ### end Alembic commands ###
