"""profile update jobs

Revision ID: 76ed20f32fe7
Revises: 220d7ae6d4f1
Create Date: 2026-09-13 05:55:44.112229

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "76ed20f32fe7"
down_revision: str | None = "220d7ae6d4f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_update_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("profile_update_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_profile_update_jobs_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_profile_update_jobs_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile_update_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profile_update_jobs_user_id"))
        batch_op.drop_index(batch_op.f("ix_profile_update_jobs_status"))

    op.drop_table("profile_update_jobs")
    # ### end Alembic commands ###
