"""media source fields

Revision ID: 95b7c3eeda93
Revises: c84aaa2b520f
Create Date: 2026-09-13 02:14:18.500390

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "95b7c3eeda93"
down_revision: str | None = "c84aaa2b520f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_file_id", sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("source_file_id")

    # ### end Alembic commands ###
