"""analysis fields

Revision ID: b07bbcab9a72
Revises: 4cbfde82e2e8
Create Date: 2026-09-13 00:36:19.995844

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b07bbcab9a72"
down_revision: str | None = "4cbfde82e2e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column("summary", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("category", sa.String(length=100), nullable=True))
        batch_op.add_column(
            sa.Column(
                "item_type",
                sa.Enum(
                    "ACTION",
                    "LEARN",
                    "READ",
                    "WATCH",
                    "IDEA",
                    "REFERENCE",
                    "SOMEDAY",
                    name="itemtype",
                    native_enum=False,
                    length=16,
                ),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("tags_json", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("importance", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("urgency", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("goal_fit", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("long_term_value", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("interest_fit", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("estimated_action_minutes", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("priority_score", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("priority_reason", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("next_action", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("suggested_due_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("language", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("confidence", sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f("ix_items_category"), ["category"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_items_priority_score"), ["priority_score"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_items_priority_score"))
        batch_op.drop_index(batch_op.f("ix_items_category"))
        batch_op.drop_column("confidence")
        batch_op.drop_column("language")
        batch_op.drop_column("suggested_due_at")
        batch_op.drop_column("next_action")
        batch_op.drop_column("priority_reason")
        batch_op.drop_column("priority_score")
        batch_op.drop_column("estimated_action_minutes")
        batch_op.drop_column("interest_fit")
        batch_op.drop_column("long_term_value")
        batch_op.drop_column("goal_fit")
        batch_op.drop_column("urgency")
        batch_op.drop_column("importance")
        batch_op.drop_column("tags_json")
        batch_op.drop_column("item_type")
        batch_op.drop_column("category")
        batch_op.drop_column("summary")
        batch_op.drop_column("title")

    # ### end Alembic commands ###
