"""source url and contents

Revision ID: c84aaa2b520f
Revises: b07bbcab9a72
Create Date: 2026-09-13 01:10:55.184308

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c84aaa2b520f"
down_revision: str | None = "b07bbcab9a72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "USER_TEXT",
                "WEB_TEXT",
                "TRANSCRIPT",
                "VISUAL_NOTES",
                "DESCRIPTION",
                "CHUNK_SUMMARY",
                name="contentkind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contents_item_id"), ["item_id"], unique=False)

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_url", sa.String(length=700), nullable=True))
        batch_op.create_unique_constraint("uq_items_user_url", ["user_id", "source_url"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_constraint("uq_items_user_url", type_="unique")
        batch_op.drop_column("source_url")

    with op.batch_alter_table("contents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contents_item_id"))

    op.drop_table("contents")
    # ### end Alembic commands ###
