"""content duration

Revision ID: d1b5bdba99a3
Revises: 95b7c3eeda93
Create Date: 2026-09-13 02:14:43.446645

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d1b5bdba99a3"
down_revision: str | None = "95b7c3eeda93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("content_duration_seconds", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("content_duration_seconds")

    # ### end Alembic commands ###
